<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE TelescopeData [
	<!ELEMENT TelescopeData (Telescope*) >
	<!ELEMENT Telescope (latitude, longitude) >
	<!ELEMENT latitude  (#PCDATA) >
	<!ELEMENT longitude (#PCDATA) >
	<!ATTLIST Telescope name CDATA #REQUIRED>
]>
<TelescopeData>
	<Telescope name="ukirt">
		<latitude>19.826</latitude>
		<longitude>-155.473</longitude>
	</Telescope>
	<Telescope name="jcmt">
		<latitude>19.826</latitude>
		<longitude>-155.473</longitude>
	</Telescope>
	<Telescope name="gemini-north">
		<latitude>19.820</latitude>
		<longitude>-155.471</longitude>
	</Telescope>
</TelescopeData>